### ISSUE TITLE
KeyError: 'ATA'

### ISSUE THREAD

**Issue by SaLuci** [titulebolide/crypto-bot#7]
Hey, its me again ;)

the bug mentioned in #5 is fixed, however a new one appeared.

Theres a coin called ATA, which is not "tradable" yet, but you can get them if you stake BNB.
So the EUR/USD Value of those coins will be zero, till they become "tradable". I think thats the Problem.

I will probably take a look at the code myself in the evening, should be a simple fix. (just ignoring coins with a USD value of zero)

**Comment by titulebolide** [comment]
What is the error log? Because I'm not sure if just don't shows up in the tickers or if it is another problem

**Comment by SaLuci** [comment]
Sorry, i forgot to add the Error log.
```
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    cli()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "main.py", line 76, in output
    figname = bot.crypto.plot_symbol(reports, symbol, relative, days)
  File "/home/ubuntu/binance-report-bot/bot/crypto.py", line 124, in plot_symbol
    ticker = report['tickers'][symbol]
KeyError: 'ATA'
```
here it is.

**Comment by titulebolide** [comment]
Which command were you calling with which options?

**Comment by SaLuci** [comment]
i was calling `python3 main.py output --symbol '*'`

**Comment by titulebolide** [comment]
Ha yeah that makes sense. Have you added ATA to the COINS list after setting up the bot?

**Comment by SaLuci** [comment]
Yeah, i did. 
After I got the error message I added ATA, but i didnt change.
if i do `python3 main.py output --symbol EOS` its working like normal

**Comment by titulebolide** [comment]
You get the error message about missing ATA before having it in the COINS?
Because the routine sums up to this:
```python
if symbol == '*':
  symbol = conf.COINS
[...]
for symbol in symbols:     
  for report in reports:
    ticker = report['tickers'][symbol]
```

**Comment by SaLuci** [comment]
wait a sec, let me remove it again from my list....
EDIT: i just removed it and the error disappeared. i think there was a Error before it was "Tradable" on Binance.

**Comment by titulebolide** [comment]
So it might not be the same error than the one you pasted I guess...

**Comment by titulebolide** [comment]
Closing for now, please reopen when you face this issue again!
